import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Center } from '@mantine/core'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>mantineカタログ集</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <Link className="text-blue-500" href="/button">
          button
        </Link>
      </Center>
      <Center>
        <Link className="text-blue-500" href="/grid">
          grid
        </Link>
      </Center>
    </div>
  )
}
