import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import { supabase } from '../utils/supabase'
import useStore from '../store'
import Link from 'next/link'
import { Center } from '@mantine/core'
import { NextPage } from 'next'
import { DashBord } from '../components/DashBord'
import { SignupEmailForm } from '../components/SignupEmailForm'
import { UseFormReturnType } from '@mantine/form/lib/use-form'
import { IForm } from '../types'
import { ApiError } from '@supabase/gotrue-js'

const Home: NextPage = () => {
  const session = useStore((state) => state.session)
  const setSession = useStore((state) => state.setSession)
  const signupCallback = async (form: UseFormReturnType<IForm>) => {
    const { error } = await supabase.auth.signUp({
      email: form.values.email,
      password: form.values.password,
    })
    return error
  }
  const signinCallback = async (form: UseFormReturnType<IForm>) => {
    const { error } = await supabase.auth.signIn({
      email: form.values.email,
      password: form.values.password,
    })
    return error
  }
  useEffect(() => {
    setSession(supabase.auth.session())
    // ユーザがログイン、ログアウトなどのアクションを行うたびにonAuthStateChange内の処理を実施する
    supabase.auth.onAuthStateChange((_event, session) => {
      // 新しいセッション情報を受け取り更新する
      setSession(session)
    })
  }, [setSession])
  return (
    <div className={styles.container}>
      <Head>
        <title>mantineカタログ集</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <DashBord />
      ) : (
        <SignupEmailForm
          signupCallback={signupCallback}
          signinCallback={signinCallback}
        />
      )}
      <Center>
        <Link className="text-blue-500" href="/button">
          button
        </Link>
      </Center>
      <Center>
        <Link className="text-blue-500" href="/grid">
          grid
        </Link>
      </Center>
    </div>
  )
}
export default Home
